# Generated by Django 4.0.3 on 2065-03-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0002_alter_attendance_attendenceid_alter_batch_batchid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
